#!/bin/bash

ALIASES="$HOME/repos/dotfiles/aliases.txt"

_complete_run()
{
  local all_aliases=()
  while IFS= read -r line; do
    all_aliases+=("$line")
  done <<< "$(sed -e 's/^\([^ ]*\) /\1:/g' $ALIASES 2>/dev/null)"

  _describe "aviable aliases"  all_aliases
}

_exec_comand() 
{

  local result

  result=$(sed -n "s/^$1 \\(.*\\)/\\1/p" "$ALIASES" 2>/dev/null)

  if [ -z "$result" ]; then
    (>&2 echo -e "unknown alias $1") && return 1;
  fi

  echo "run: $result"

  eval $result
}

run()
{

  case $1 in
    *) 
      _exec_comand "$1"
      ;;
     
  esac

}

compdef '_complete_run' run
