syntax on
" hi Normal guibg=NONE ctermbg=NONE
"color transparent

set number
set expandtab
set tabstop=4
set smarttab
set softtabstop=4
set shiftwidth=4
set colorcolumn=121
highlight ColorColumn guibg=LightYellow

let mapleader = "\<Space>"


set hlsearch
set incsearch
set ignorecase

set autoread
au CursorHold * checktime

"mapping
inoremap <C-o> <esc>o
imap <C-l> <esc>A{<CR>
imap <C-e> <esc>A;<CR>

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
" Ctrl-j/k deletes blank line below/above, and Alt-j/k inserts.
nnoremap <silent><C-j> m`:silent +g/\m^\s*$/d<CR>``:noh<CR>
nnoremap <silent><C-k> m`:silent -g/\m^\s*$/d<CR>``:noh<CR>

nnoremap <silent><C-h> :call coc#float#close_all()<CR>

set encoding=utf-8

map m <Plug>(easymotion-prefix)


nnoremap <Leader>l :ls<CR>
nnoremap <TAB> :bn<CR>
nnoremap <S-TAB> :bp<CR>
nnoremap <Leader>g :e#<CR>
nnoremap <Leader>d :bp \| bd # <CR>

nnoremap <Leader>sw Pldw

let g:arc_prefix = 'https://a.yandex-team.ru/arc/'
function GetFileLink()
  let l:file_name = expand('%:p')
  let l:nodes = split(l:file_name, '/')
  if len(l:nodes) > 2 && l:nodes[0] ==# 'home' && l:nodes[1] ==# 'dyusudakov' && l:nodes[2] ==# 'arcadia'
    let l:link = g:arc_prefix . 'trunk/' . join(l:nodes[2:], '/') 
    echo l:link
  else
    echo 'cant get arc link =_('
  endif
endfunction

nnoremap <F4> :call GetFileLink()<CR>

nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>

if &diff
  highlight DiffAdd    cterm=NONE ctermbg=22  ctermfg=NONE guibg=#143d14 guifg=NONE
  highlight DiffDelete cterm=NONE ctermbg=52  ctermfg=NONE guibg=#3d1414 guifg=NONE
  highlight DiffChange cterm=NONE ctermbg=23  ctermfg=NONE guibg=#14333d guifg=NONE
  highlight DiffText   cterm=bold ctermbg=24 ctermfg=NONE guibg=#245b70 guifg=NONE
endif

