#!/bin/bash

# Path to your lockscreen script
LOCK_SCRIPT="$HOME/repos/dotfiles/lockscreen.sh"

echo "Display configuration changed. Running lockscreen and wallpaper update."
feh --bg-fill "$HOME/Pictures/wallpaper.png"

if pgrep -x "i3lock" > /dev/null; then
    echo "Screen is locked. Updating lockscreen image..."
    kill $(pidof i3lock)
    bash "$LOCK_SCRIPT"
fi
