keys:
  - &laptop-personal age1t4edfzxrysffldx8yy39ggr5zp4qu54mj2x5r8l820nc8zr48fesn9rxke
  - &desktop-personal age1jcef3l8lkgp490xrxrkkzhvmpj0xc57sfyar4qzhrrpkqg2afcdssvyxsg
  - &laptop-work age19u5s35v3durs6qpmy9vuu0m42lqze7w84gn7t0rqfk4hlzmfuu4qhs9hc9
creation_rules:
  - path_regex: secrets/vpn_config\.json$
    key_groups:
      - age: 
        - *laptop-personal
        - *laptop-work
        - *desktop-personal
  - path_regex: secrets/user\.json$
    key_groups:
      - age: 
        - *laptop-personal
        - *laptop-work
        - *desktop-personal
